#!/usr/bin/php
<?php
$par  =  "p:";
$par  .=  "d:";
$options = getopt($par);
//print_r( $options);
//$data = trim($options["d"]);
$data=($options["d"]);

$info = <<<EOD

archeiogiainsertstinvassi

    INFO: data for mongodb
    OPTIONS:
        -d data

EOD;
if(!$options['d'] ){
        echo $info;
        die;
}


$dataArray = json_decode($data,true);

$m = new MongoClient();
$db = $m->diyiot_sensorsData;
//$sensor_coll = $db->$dataArray['devID'];
$collection = $db->mycol;
// create a unique index on timestamp
//$sensor_coll->ensureIndex(array('timestamp' => 1));
//$sensor_rec = array( "Direction" => $dataArray['direction'], "Rad" => $dataArray['rad'],"Coordinates" => $dataArray['Coordinates']);       
$collection->insert($dataArray);
echo $dataArray;

die();
?>

